apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-canary
spec:
  type: {{.Values.serviceType}}
  ports:
  - name: http-canary
    port: 8080
    targetPort: http
    protocol: TCP
  selector:
    app: {{.Values.name}}
    harness.io/track: canary
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-stable
spec:
  type: {{.Values.serviceType}}
  ports:
  - name: http-stable
    port: 8080
    targetPort: http
    protocol: TCP
  selector:
    app: {{.Values.name}}
    harness.io/track: stable
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{.Values.name}}-canary
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /{{.Values.virtualPath}}/canary/(.*)
        backend:
          serviceName: {{.Values.name}}-canary
          servicePort: http-canary
---
#
# Ingress targeting stable only, at /api/*
#
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{.Values.name}}-stable
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /{{.Values.virtualPath}}/api/(.*)
        backend:
          serviceName: {{.Values.name}}-stable
          servicePort: http-stable